repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
    - id: ruff
      name: run linter
      args: [ --fix, --show-fixes ]
    - id: ruff-format
      name: run formatter
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    args: [--check-untyped-defs]
    additional_dependencies:
      [
        # main dependencies
        click,
        datasets,
        httpx,
        huggingface-hub,
        loguru,
        numpy,
        protobuf,
        pydantic,
        pydantic-settings,
        pyyaml,
        safetensors,
        torch,
        transformers,

        # dev dependencies
        pytest,
        pydantic_settings,
        respx,
        setuptools,
        setuptools-git-versioning,

        # types
        types-click,
        types-PyYAML,
      ]
